### ISSUE TITLE
`Symbol` case class is nucleotide-centric

### ISSUE THREAD

**Issue by laserson** [bigdatagenomics/adam#672] opened 2015-05-04 19:06 UTC
Not sure if this really matters, but just wanted to address that the `Symbol` class in the new `Alphabet` machinery includes a "complement" field, which doesn't make sense for proteins or other things (e.g., secondary structure).  Perhaps necessary to subclass `Alphabet`?  Thoughts?

**Comment by massie** [comment] 2015-05-04 20:29
Agree. Should we consider incorporating BioScala into ADAM? 

https://github.com/bioscala/bioscala

It's BSD licensed.

**Comment by fnothaft** [comment] 2015-05-04 20:42
I don't know of anyone using ADAM for proteomic or RNA secondary structure work, so I'm inclined to not make another change for now.

BioScala does look like an attractive package if we were to go that route, but it doesn't look like it is actively being developed. CCing @antonkulaga who I see has committed there a lot, who might know more about the status of the BioScala project.

**Comment by laserson** [comment] 2015-05-04 20:42
I'm not familiar with that project, but I'm not opposed.  Also, what about the issue of persisting Alphabet information?

**Comment by fnothaft** [comment] 2015-05-04 20:45
> Also, what about the issue of persisting Alphabet information?

Sorry, I didn't follow here. What do you mean by that?

**Comment by laserson** [comment] 2015-05-04 20:47
Sorry, just thinking aloud.  Wondering whether it'd be useful to model Alphabets at the Avro level.  But that's probably unnecessary complication...

**Comment by fnothaft** [comment] 2015-05-04 20:51
@laserson we used to have a `Base` enum in the Avro level, but it wound up not being terribly useful so we scrapped it in https://github.com/bigdatagenomics/bdg-formats/pull/46. If I could TL;DR my experiences with `enum` based alphabets, the problem is that strings are _reasonably_ efficient and a fair bit easier to work with.

**Comment by fnothaft** [comment] 2015-05-05 01:49
Also, I would say that it would probably be sufficient to just break the "reverse complement-able" section of alphabets out into another trait. E.g., you'd have `Alphabet` and `ComplementableAlphabet` or something of the like.

**Comment by fnothaft** [comment] 2015-06-24 23:57
Do we want to keep this open or close it? IMO, this is not a problem for now. I think we should close it and reopen it later if we decide to work with protein sequences/etc.

**Comment by fnothaft** [comment] 2016-07-06 18:47
Closing as won't fix.

**Closed by fnothaft** 2016-07-06 18:47 UTC
Labels: wontfix
