### ISSUE TITLE
adam-submit VerifyError

### ISSUE THREAD

**Issue by simplelive** [bigdatagenomics/adam#642] opened 2015-04-06 16:31 UTC
Hadoop:
	Hadoop 2.6.0

Spark:
	Spark 1.3.0 built for Hadoop 2.6.0

[root@V1 ~]# adam-submit vcf2adam small.vcf hdfs://V1:9000/small.adam ;
2015-04-07 00:23:06 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.lang.VerifyError: class org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$AddBlockRequestProto overrides final method getUnknownFields.()Lcom/google/protobuf/UnknownFieldSet;
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
        at java.lang.Class.privateGetPublicMethods(Class.java:2733)
        at java.lang.Class.privateGetPublicMethods(Class.java:2743)
        at java.lang.Class.getMethods(Class.java:1472)
        at sun.misc.ProxyGenerator.generateClassFile(ProxyGenerator.java:426)
        at sun.misc.ProxyGenerator.generateProxyClass(ProxyGenerator.java:323)
        at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:672)
        at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:592)
        at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:244)
        at java.lang.reflect.WeakCache.get(WeakCache.java:141)
        at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:455)
        at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:738)
        at org.apache.hadoop.ipc.ProtobufRpcEngine.getProxy(ProtobufRpcEngine.java:105)
        at org.apache.hadoop.ipc.RPC.getProtocolProxy(RPC.java:570)
        at org.apache.hadoop.hdfs.NameNodeProxies.createNNProxyWithClientProtocol(NameNodeProxies.java:420)
        at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:316)
        at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:178)
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:665)
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:601)
        at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:148)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2596)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:91)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2630)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2612)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:296)
        at org.apache.hadoop.mapreduce.lib.output.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:145)
        at org.apache.spark.rdd.InstrumentedOutputFormat.checkOutputSpecs(InstrumentedOutputFormat.scala:38)
        at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopDataset(PairRDDFunctions.scala:976)
        at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopFile(PairRDDFunctions.scala:903)
        at org.apache.spark.rdd.InstrumentedPairRDDFunctions.saveAsNewAPIHadoopFile(InstrumentedPairRDDFunctions.scala:466)
        at org.bdgenomics.adam.rdd.ADAMRDDFunctions$$anonfun$adamParquetSave$1.apply$mcV$sp(ADAMRDDFunctions.scala:90)
        at org.bdgenomics.adam.rdd.ADAMRDDFunctions$$anonfun$adamParquetSave$1.apply(ADAMRDDFunctions.scala:71)
        at org.bdgenomics.adam.rdd.ADAMRDDFunctions$$anonfun$adamParquetSave$1.apply(ADAMRDDFunctions.scala:71)
        at org.apache.spark.rdd.Timer.time(Timer.scala:57)
        at org.bdgenomics.adam.rdd.ADAMRDDFunctions.adamParquetSave(ADAMRDDFunctions.scala:71)
        at org.bdgenomics.adam.rdd.ADAMRDDFunctions.adamParquetSave(ADAMRDDFunctions.scala:57)
        at org.bdgenomics.adam.cli.Vcf2ADAM.run(Vcf2ADAM.scala:75)
        at org.bdgenomics.adam.cli.ADAMSparkCommand$class.run(ADAMCommand.scala:57)
        at org.bdgenomics.adam.cli.Vcf2ADAM.run(Vcf2ADAM.scala:54)
        at org.bdgenomics.adam.cli.ADAMMain$.main(ADAMMain.scala:107)
        at org.bdgenomics.adam.cli.ADAMMain.main(ADAMMain.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:569)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:166)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:189)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:110)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by massie** [comment] 2015-04-06 16:42
This is likely an incompatibility between Spark and protobuf (see
http://apache-spark-user-list.1001560.n3.nabble.com/Spark-1-1-1-Hadoop-2-6-Protobuf-conflict-td20656.html
).

Did you build ADAM from source our use a released version, which version?
If you built it yourself, what command did you issue to build?


-Matt

**Comment by simplelive** [comment] 2015-04-07 01:41
Date:
2015-04-01

# git clone https://github.com/bigdatagenomics/adam

# mvn clean package -DskipTests

CHANGES.md last two lines:

# ADAM #
* ISSUE [570](https://github.com/bigdatagenomics/adam/pull/570): A few small conversion fixes

**Comment by heuermh** [comment] 2015-11-02 20:44
@simplelive could you try again with git head (currently version 0.18.2-SNAPSHOT) or a recent distribution (latest is 0.18.1)?  I am not able to reproduce.

**Comment by fnothaft** [comment] 2016-07-06 15:33
Closing as unable to reproduce.

**Closed by fnothaft** 2016-07-06 15:33 UTC
