### ISSUE TITLE
Write quick start guide for Cloudera Manager/CDH5

### ISSUE THREAD

**Issue by massie** [bigdatagenomics/adam#42] opened 2014-01-12 23:56 UTC
We should have simple step-by-step instructions (or a script) for deploying ADAM on CDH4 and CDH5. 

There is a wiki page that outlines the steps to run ADAM on EC2 which could be useful as a starting point.

https://github.com/massie/adam/wiki/Running-ADAM-on-EC2

**Comment by benedictpaten** [comment] 2015-01-20 19:42
Did this get done already? We have a student interested in doing this as a learning exercise.

**Comment by laserson** [comment] 2015-01-20 19:47
Not to my knowledge. It'd be great to include Cloudera Director too, for
provisioning clusters.

**Comment by fnothaft** [comment] 2015-01-20 19:48
I think it is here: https://github.com/bigdatagenomics/adam/blob/master/docs/source/50_running_on_CDH.md

**Comment by benedictpaten** [comment] 2015-01-21 00:40
Thanks Frank, Zim (cc'd) I think you should probably pick a different
issue.

**Comment by laserson** [comment] 2015-01-21 01:09
That said, a quick scan through the doc makes it look a bit outdated from
the style we promote now.  Would be great to switch to adam-submit.  Also,
on CDH, we probably would prefer using YARN rather than Spark standalone
mode.

**Comment by fnothaft** [comment] 2015-01-21 01:10
+1 @laserson

**Comment by fnothaft** [comment] 2016-08-25 05:13
Closing as dupe of #493.

**Closed by fnothaft** 2016-08-25 05:13 UTC
Labels: duplicate
