### ISSUE TITLE
bucketing strategy

### ISSUE THREAD

**Issue by jpdna** [bigdatagenomics/adam#1553] opened 2017-05-30 17:07 UTC
An issue that we discussed in that past, but I am not sure if we ever prototyped:

I'd like to try writing parquet files from the soon to be ready ADAM dataset api, bucketed by 10 megabase genomic regions using `df.write.bucketyby()` available in Spark 2.1 , and then compare "random access" performance of lookup and joins (hopefully through partition discovery here: https://spark.apache.org/docs/latest/sql-programming-guide.html#partition-discovery ) use a "chr_bin" filter in a query - as compared with the normal parquet predicate pushdown.

I'll go ahead and experiment with this - but wanted to get anyone else's thoughts on if this seems viable or worthwhile.  I'm hoping to achieve the effect here of a very course index.

**Comment by fnothaft** [comment] 2017-06-22 20:13
Hi @jpdna! I think this is a dupe of #651. I'm closing it as a dupe, but please reopen if you disagree.

**Closed by fnothaft** 2017-06-22 20:13 UTC
Labels: duplicate
