### ISSUE TITLE
migration converters

### ISSUE THREAD

**Issue by antonkulaga** [bigdatagenomics/adam#1629] opened 2017-07-24 11:32 UTC
I convert many large files to adam format, but when new adam release is coming out everything breaks because of different avro and parquet versions. Is there any migation tools/code to convert files between adam releases?

**Comment by heuermh** [comment] 2017-07-24 19:46
See #338 and #345.  Once we reach version 1.0 the formats will be considered stable, we will enforce semantic versioning, and will provide conversion tools for any schema changes.  Meanwhile perhaps there may be generic Avro tools that could help with migration?  Ping @massie

**Comment by heuermh** [comment] 2017-07-26 17:25
After a little digging, looks like the [Apache HiFi](https://nifi.apache.org/docs.html) project may support Avro schema transforms, e.g.

https://nifi.apache.org/docs/nifi-docs/components/org.apache.nifi/nifi-kite-nar/1.3.0/org.apache.nifi.processors.kite.ConvertAvroSchema/additionalDetails.html

**Comment by fnothaft** [comment] 2018-03-07 23:00
Closing as a dupe of #345.

**Comment by fnothaft** [comment] 2018-03-07 23:00
Closing as a dupe of #345.

**Closed by fnothaft** 2018-03-07 23:00 UTC
Labels: duplicate
