### ISSUE TITLE
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 351 in stage 0.0 failed 1 times, most recent failure: Lost task 351.0 in stage 0.0 (TID 351, localhost): 

### ISSUE THREAD

**Issue by dbl001** [bigdatagenomics/adam#836] opened 2015-09-27 04:01 UTC
Hi,

I'm on OS X 10.10.5.
Java 1.8.
Spark 1.5
Scala 2.11
Maven 3.2.1

I'm running a transform operation with 'adam' which is an example in the O'Reilly book 'Advanced Analytics with Spark':

```
bin/adam-submit transform /users/davidlaxer/genomics/HG00103.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam /users/davidlaxer/genomics/reads/HG00103
```
I got this error:

```
Sep 26, 2015 8:35:06 PM INFO: org.apache.parquet.hadoop.ColumnChunkPageWriteStore: written 106B for [failedVendorQualityChecks] BOOLEAN: 253,719 values, 31,723B raw, 74B comp,15/09/26 20:35:06 ERROR executor.Executor: Exception in task 351.0 in stage 0.0 (TID 351)
htsjdk.samtools.FileTruncatedException: Premature end of file
```
with this stack trace:
```
at htsjdk.samtools.util.BlockCompressedInputStream.readBlock(BlockCompressedInputStream.java:382)
	at htsjdk.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:127)
	at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:252)
	at htsjdk.samtools.util.BinaryCodec.readBytesOrFewer(BinaryCodec.java:404)
	at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:380)
	at htsjdk.samtools.util.BinaryCodec.readByteBuffer(BinaryCodec.java:490)
	at htsjdk.samtools.util.BinaryCodec.readInt(BinaryCodec.java:501)
	at htsjdk.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:177)
	at org.seqdoop.hadoop_bam.BAMRecordReader.nextKeyValue(BAMRecordReader.java:176)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.hasNext(NewHadoopRDD.scala:143)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:39)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply$mcV$sp(PairRDDFunctions.scala:1034)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1034)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1034)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1206)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1042)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1014)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
15/09/26 20:35:07 WARN spark.ThrowableSerializationWrapper: Task exception could not be deserialized
java.lang.ClassNotFoundException: htsjdk.samtools.FileTruncatedException
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:340)
	at org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:67)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.apache.spark.ThrowableSerializationWrapper.readObject(TaskEndReason.scala:163)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1896)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:72)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:98)
	at org.apache.spark.scheduler.TaskResultGetter$$anon$3$$anonfun$run$2.apply$mcV$sp(TaskResultGetter.scala:108)
	at org.apache.spark.scheduler.TaskResultGetter$$anon$3$$anonfun$run$2.apply(TaskResultGetter.scala:105)
	at org.apache.spark.scheduler.TaskResultGetter$$anon$3$$anonfun$run$2.apply(TaskResultGetter.scala:105)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1697)
	at org.apache.spark.scheduler.TaskResultGetter$$anon$3.run(TaskResultGetter.scala:105)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
15/09/
```

Is the file corrupted?

**Comment by fnothaft** [comment] 2015-09-27 15:31
Hi @dbl001!

Can you try loading this file with [samtools](https://samtools.github.io/)? E.g., `samtools flagstat /users/davidlaxer/genomics/HG00103.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam`. If you have Homebrew installed, you should be able to `brew install samtools`. If samtools can read the file OK, then the issue is somewhere in ADAM. Else, the issue is that the file is corrupted.

**Comment by dbl001** [comment] 2015-09-27 15:37
Ok.  I downloaded samtools 1.2.1 with Macports.  Is that ok?

Here’s the size and sum of the original input file and the file after loading it into HDFS:

```

$ ls -l ~/Downloads/*.bam
-rw-r--r--  1 davidlaxer  staff  11804295270 Sep 24 22:33 /Users/davidlaxer/Downloads/HG00103.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam
David-Laxers-MacBook-Pro:examples davidlaxer$ sum !$
sum ~/Downloads/*.bam
12016 11527633 /Users/davidlaxer/Downloads/HG00103.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam

David-Laxers-MacBook-Pro:examples davidlaxer$ hadoop fs -ls  /users/davidlaxer/genomics
Found 2 items
-rw-r--r--   1 root       staff 11804295270 2015-09-26 09:03 /users/davidlaxer/genomics/HG00103.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam
drwxr-xr-x   - davidlaxer staff         102 2015-09-26 18:00 /users/davidlaxer/genomics/reads

```

**Comment by fnothaft** [comment] 2015-09-27 15:38
> Ok.  I downloaded samtools 1.2.1 with Macports.  Is that ok?

Yep; that is OK!
I would expect the HG00103 file to be approximately 15GB in size. Most of the 1000 Genomes WGS files are around that size.

**Comment by dbl001** [comment] 2015-09-27 15:59
11,804,295,270 Hmmm!  Bad File!

The book says the file is 16 GB.  ‘curl’ says 15.8gb.

$ curl -O ftp://ftp.ncbi.nih.gov/1000genomes/ftp/phase3/data/HG00103/alignment/HG00103.mapped.ILLUMINA.bwa.GBR\.low_coverage.20120522.bam
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  1 15.8G    1  210M    0     0  5584k      0  0:49:43  0:00:38  0:49:05 5591k

**Comment by ryan-williams** [comment] 2015-09-28 16:05
So is the resolution that @dbl001 had a bad input file? Should we close this then?

**Comment by dbl001** [comment] 2015-09-28 16:11
Yes, thank you!

**Comment by ryan-williams** [comment] 2015-09-28 16:12
np, thx @dbl001

**Closed by ryan-williams** 2015-09-28 16:12 UTC
