### ISSUE TITLE
add -single file output option to ADAM2Vcf

### ISSUE THREAD

**Issue by jpdna** [bigdatagenomics/adam#1102] opened 2016-08-07 14:07 UTC
Add a `-single` option to `ADAM2Vcf` to output a single VCF file.
I assume this can be done similarly to how it is done currently for BAM output.

@fnothaft - let us know what you think the best approach is here.  I am willing to work on porting over to VCF, but I know this was a finicky bit of code, so if you'd rather do it or if you have suggestions let me know.

My near term goal here is to examine the VCF transformations/roundtrips using each of Parquet and HBase data stores, both of which can make use of this same code for VCF output.

**Comment by fnothaft** [comment] 2016-08-08 04:07
I'm going to close this as a dupe of #1009. Thanks for opening it; it gave me the impetus to get back to fixing this. I should have a PR tomorrow.

**Closed by fnothaft** 2016-08-08 04:07 UTC
Labels: duplicate
