### ISSUE TITLE
please add maven-source-plugin into the pom file

### ISSUE THREAD

**Issue by Fei-Guang** [bigdatagenomics/adam#1239] opened 2016-11-04 03:24 UTC
currently , i copy all the source files manually  then  use jar to package the source jar 
`D:\adam-adam-parent-spark2_2.11-0.20.0>jar cvf adam-2.11-0.20
.0-sources.jar -C source/ . `

please add maven-source-plugin into the pom file to package the source

**Comment by Fei-Guang** [comment] 2016-11-04 03:37
>>>Hi @Fei-Guang! Where are you running that? Are you running that in spark-shell? ADAM relies on a >>>custom Kryo serializer Registrator for serialization. If you use ./bin/adam-shell, this starts a Spark >>>shell >>>where the serialization config (and classpath) are set up.

i run it in idea,  how to register a Kryo serializer  in idea?

**Comment by heuermh** [comment] 2016-11-04 10:25
The maven-source-plugin is already included in the ADAM build.

To build on top of ADAM, I would suggest copying liberally from the project structure of either
https://github.com/heuermh/adam-examples
  or
https://github.com/heuermh/adam-commands

The READMEs of both need an update for Spark 2.x and ADAM version 0.20.0, I'll do that and push shortly.

**Comment by fnothaft** [comment] 2016-11-05 22:07
OOC, are you depending on `adam-parent` instead of `adam-{core, apis, cli}`? `adam-parent` is a POM only dependency and should not be used.

**Comment by fnothaft** [comment] 2016-11-20 04:52
Closing as not a bug.

**Closed by fnothaft** 2016-11-20 04:52 UTC
