### ISSUE TITLE
Interval tree join in ADAM

### ISSUE THREAD

**Issue by jpdna** [bigdatagenomics/adam#1171] opened 2016-09-14 19:20 UTC
When reviewing:
#1109

it got me thinking more about the interval tree based joins of Mango and described at
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4741060/pdf/12859_2016_Article_904.pdf 

If we already have implemented such interval tree based joins in ADAM and or Mango can you point me to it?

If not - are there join scenarios where it would be more favorable  to load up the data into an RDD of  Mango's interval tree data structures  prior to doing an interval overlap join of the types in #1109 ?

@akmorrow13 do you have thoughts on this?

**Comment by fnothaft** [comment] 2016-11-08 16:52
Closing as dupe of #1224.

**Closed by fnothaft** 2016-11-08 16:52 UTC
