### ISSUE TITLE
Sub-partitioning of Parquet file for ADAM

### ISSUE THREAD

**Issue by jpdna** [bigdatagenomics/adam#1003] opened 2016-04-18 12:15 UTC
The Spark-SQL programming guide describe an optimization of parquet usage that involves splitting parquet file into directories corresponding to different column values. [here](http://spark.apache.org/docs/latest/sql-programming-guide.html#partition-discovery)

This issue is meant as a place for discussion of this topic and to determine if we should prototype such a parquet directory layout, for example dividing the parquet file into individual files per chromosome.

Look forward to any comments and/or links to earlier discussions of this topic

**Comment by fnothaft** [comment] 2016-07-06 16:02
Closing as dupe of #651.

**Closed by fnothaft** 2016-07-06 16:02 UTC

**Comment by heuermh** [comment] 2016-07-21 03:40
@jpdna Take a look at https://github.com/tomwhite/genomics-analytics/blob/master/adam.md

**Comment by tomwhite** [comment] 2016-07-22 09:42
@jpdna @heuermh that's pretty old now - I think using Spark to do the partitioning is the way forward, and Impala supports nested types so flattening is not necessary. See https://github.com/bigdatagenomics/adam/issues/651#issuecomment-93486125
