### ISSUE TITLE
toCoverage() function for alignments does not distinguish samples

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/adam#2049] opened 2018-09-13 19:56 UTC
If one was to load a glob of alignment files, and call[ `toCoverage()`](https://github.com/bigdatagenomics/adam/blob/559ea13f3ff9c0bb856eb9598bf8eec3d2f26272/adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala#L337), this would calculate total coverage across all individual files. Ideally, we would keep information of the origin file, and there would be a separate coverage record for each sample.

**Comment by heuermh** [comment] 2018-09-21 17:17
Closing as duplicate of #1498.

**Closed by heuermh** 2018-09-21 17:17 UTC
Labels: enhancement
